[font]
size = 12

# [font.bold]
# family = "Iosevka"
# style = "Bold"

# [font.normal]
# family = "Iosevka"
# style = "Medium"

[font.bold]
family = "Iosevka J2"
style = "Bold"

[font.normal]
family = "Iosevka J2"
style = "Medium"

# [font.bold]
# family = "NK57 Monospace"
# style = "Condensed Bold"

# [font.normal]
# family = "NK57 Monospace"
# style = "Condensed"

# [font.bold]
# family = "Jetbrains Mono"
# style = "Bold"

# [font.normal]
# family = "Jetbrains Mono"
# style = "Medium"

# [font.bold]
# family = "Input Mono Condensed"
# style = "Medium"

# [font.normal]
# family = "Input Mono Condensed"
# style = "Regular"

[window]
decorations = "buttonless"
dynamic_title = false
option_as_alt = "Both"

[window.padding]
x = 5
y = 5

[cursor.style]
blinking = "Off"
shape = "Block"

[colors]
draw_bold_text_with_bright_colors = false
